apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-platform-backend
  namespace: default
  labels:
    app: ml-platform-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-platform-backend
  template:
    metadata:
      labels:
        app: ml-platform-backend
    spec:
      containers:
        - name: backend
          image: docker.io/loihoangthanh1411/ml-platform-backend:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-platform-frontend
  namespace: default
  labels:
    app: ml-platform-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-platform-frontend
  template:
    metadata:
      labels:
        app: ml-platform-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/loihoangthanh1411/ml-platform-frontend:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
